### ISSUE TITLE
Easy way to get to the end of the recording

### ISSUE THREAD

**Issue by zhuberty** [arthurwolf/annotator#7]
We don't have an easy way to do this. Dragging the timeline cursor to the end doesn't seem to do this reliably.

**Comment by zhuberty** [comment]
I figured out how to do this though it's not super intuitive. We can drag the asciinema playback to the end and it rounds it to the nearest 15 seconds. Then we can/hold hit the right arrow key to get to the actual end of the recording.

For additional context - the timeline that is shown below the recording playback doesn't actually end - it just goes on forever if you keep dragging the orange cursor bar to the right.

**Comment by arthurwolf** [comment]
Currently should work with the "End" key, reopen if unsatisfactory, thanks @zhuberty !
