### ISSUE TITLE
Feature request: button to switch timeline from hours to seconds

### ISSUE THREAD

**Issue by zhuberty** [arthurwolf/annotator#8]
The recording file shows entries in seconds. So, the thought here is to be able to inspect the file and easily navigate to the time in seconds using the timeline.

**Comment by arthurwolf** [comment]
I don't get this one.

Currently, the timeline is in seconds, the player is in seconds, and the file records in seconds (well, milliseconds for the annotations).

I'm not sure what you mean about hours.

Mind clarifying @zhuberty ? I might be missing something obvious.

**Comment by zhuberty** [comment]
I don't think is my request is too helpful. Milliseconds should be fine. Maybe seconds would suffice.
